name: travis-action
env:
  CONFIG: "release"
  VERA: false
  SUFFIX: "" 
  QMAKE_EXTRA: ""
  CELLAR_CACHE_DIR: "Unchanged" 
  #$([ $TRAVIS_OS_NAME = 'osx' ] && echo "/usr/local/Cellar" || { mkdir -p .empty/{qt,ccache,python@2,python@3} ; echo .empty ; } )

on: [push]

jobs:
  Linux:
    
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set CELLAR_CACHE_DIR
       ${{env.CELLAR_CACHE_DIR}}=".empty"
      if: runner.os == "macOS"
      run: |
        ${{env.CELLAR_CACHE_DIR}}="/usr/local/Cellar"
        echo ${{env.CELLAR_CACHE_DIR}}
      
    
