name: travis-action
env:
  SCRIPTS_PATH: "./workflow_scripts"
  VERA: false
  SUFFIX: "" 
  QMAKE_EXTRA: ""
  
on: [push]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        configs: [release, debug]
        exclude:
        - os: macos-latest
          configs: debug

    runs-on: ${{ matrix.os }}
    env:
      CONFIG: ${{ matrix.configs }}

    steps:
    - uses: actions/checkout@v2
    - name: Set enviroment
      run: |
        export CELLAR_CACHE_DIR=$([ $runner.os = 'macOS' ] && echo "/usr/local/Cellar" || { mkdir -p .empty/{qt,ccache,python@2,python@3} ; echo .empty ; } )
    - name: install
      run: $SCRIPTS_PATH/install.sh ${{ runner.os }}
    - name: script
      run: $SCRIPTS_PATH/script.sh
    - name: after_script
      run: $SCRIPTS_PATH/after_script.sh
    - name: after_success
      run: if [ "$CONFIG" = "debug" ]; then codecov; fi
      
