name: travis-action
env:
  SCRIPTS_PATH: "./workflow_scripts"
  CONFIG: "release"
  VERA: false
  SUFFIX: "" 
  QMAKE_EXTRA: ""
  CELLAR_CACHE_DIR: "Unchanged" 
  #$([ $TRAVIS_OS_NAME = 'osx' ] && echo "/usr/local/Cellar" || { mkdir -p .empty/{qt,ccache,python@2,python@3} ; echo .empty ; } )

on: [push]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        configs: [release, debug]

    runs-on: ${{ matrix.os }}
    env:
      IS_MACOS: contains(matrix.os, "macos")
      if: (IS_MACOS && matrix.configs == debug) == 0
    steps:
    - uses: actions/checkout@v2
    - name: Set enviroment
      run: export CONFIG=$matrix.configs
    - name: install
      run: $SCRIPTS_PATH/install.sh
    - name: script
      run: $SCRIPTS_PATH/script.sh
    - name: after_script
      run: $SCRIPTS_PATH/after_script.sh
    - name: after_success
      run: if [ "$CONFIG" = "debug" ]; then codecov; fi
      
