name: travis-action
env:
  CONFIG: "release"
  VERA: false
  SUFFIX: "" 
  QMAKE_EXTRA: ""
  CELLAR_CACHE_DIR: "Unchanged" 
  #$([ $TRAVIS_OS_NAME = 'osx' ] && echo "/usr/local/Cellar" || { mkdir -p .empty/{qt,ccache,python@2,python@3} ; echo .empty ; } )

on: [push]

jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        configs: [release, debug]

    runs-on: ${{ matrix.os }}
    if: ! (runner.os == "macOS" && matrix.configs == debug)
    steps:
    - uses: actions/checkout@v2
    - name: Set enviroment
      run: export CONFIG=$matrix.configs
    - name: install
      run: ./.travis/install.sh
    - name: script
      run: ./.travis/script.sh
    - name: after_script
      run: ./.travis/after_script.sh
    - name: after_success
      run: if [ "$CONFIG" = "debug" ]; then codecov; fi
      
    
